language: python
python:
  - "2.7"
sudo: false
addons:
  apt:
    packages:
      - python-dev
      - python-pygments
      - libxslt1-dev
      - libxml2-dev
install:
  - git clone --depth=1 --branch=master https://github.com/tabatkins/bikeshed.git ./bikeshed
  - pip install --editable ./bikeshed
  - bikeshed update
script:
  bikeshed spec ./index.src.html
